[package]
name = "day-06-a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
substring = "1.4.5"
itertools = "0.10.5"